#!/bin/bash
echo "=== DATABASES ==="
echo "MongoDB:"
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ec2-user@mongodb.roboshop.internal "systemctl is-active mongod" 2>/dev/null || echo "inactive or not installed"
echo "MySQL:"
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ec2-user@mysql.roboshop.internal "systemctl is-active mysqld" 2>/dev/null || echo "inactive or not installed"
echo "Redis:"
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ec2-user@redis.roboshop.internal "systemctl is-active redis" 2>/dev/null || echo "inactive or not installed"
echo "RabbitMQ:"
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ec2-user@rabbitmq.roboshop.internal "systemctl is-active rabbitmq-server" 2>/dev/null || echo "inactive or not installed"
echo ""
echo "=== APPLICATIONS ==="
echo "Frontend:"
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ec2-user@frontend.roboshop.internal "systemctl is-active nginx" 2>/dev/null || echo "inactive or not installed"
echo "Catalogue:"
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ec2-user@catalogue.roboshop.internal "systemctl is-active catalogue" 2>/dev/null || echo "inactive or not installed"
echo "User:"
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ec2-user@user.roboshop.internal "systemctl is-active user" 2>/dev/null || echo "inactive or not installed"
echo "Cart:"
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ec2-user@cart.roboshop.internal "systemctl is-active cart" 2>/dev/null || echo "inactive or not installed"