---
- name: Setup MongoDB
  hosts: mongodb
  become: true
  roles:
    - mongodb

- name: Setup MySQL
  hosts: mysql
  become: true
  roles:
    - mysql

- name: Setup Redis
  hosts: redis
  become: true
  roles:
    - redis

- name: Setup RabbitMQ
  hosts: rabbitmq
  become: true
  roles:
    - rabbitmq

- name: Setup Catalogue
  hosts: catalogue
  become: true
  roles:
    - catalogue

- name: Setup User
  hosts: user
  become: true
  roles:
    - user

- name: Setup Cart
  hosts: cart
  become: true
  roles:
    - cart

- name: Setup Shipping
  hosts: shipping
  become: true
  roles:
    - shipping

- name: Setup Payment
  hosts: payment
  become: true
  roles:
    - payment

- name: Setup Dispatch
  hosts: dispatch
  become: true
  roles:
    - dispatch

- name: Setup Frontend
  hosts: frontend
  become: true
  roles:
    - frontend
